function mostrarMensagem() {
  // Obtém o elemento de entrada de número
  var numeroEscolhidoInput = document.getElementById("numeroEscolhido");



  // Obtém o valor do número escolhido
  var numeroEscolhido = parseInt(numeroEscolhidoInput.value);



  // Verifica se o número está dentro do intervalo de 1 a 10


  if (numeroEscolhido >= 1 && numeroEscolhido <= 10) {


    // Defina mensagens correspondentes para cada número


    var mensagens = [
      "O número um fala de harmonia e unidade.Deus é a fundação.Tudo começa Nele.Ninguém o precede, desse modo, o numero um representa o Deus absoluto.Para com Deus tudo é um: há um só Deus(1 Tm 2.5, Dt 6.4).A Bíblia declara a Páscoa como o início dos meses(Êx 12.2).Primeiro porque foi o tempo em que Ele veio para salvar seu povo.Todo primogênito era santo ao Senhor(Êx 22.29).Também era Sua toda primeira colheita e todo o primeiro fruto.O número um aponta para unidade, para o Deus absoluto.Ele é o único Deus.",
         
      "O três é o número da trindade; o número dois é o número do Senhor Jesus. Deus é três em um e um em três. Dentro da trindade, o Filho é a segunda pessoa. O número dois é, portanto, o número do Senhor Jesus. O dois tem um significado semelhante ao oito. A Palavra do Senhor diz, na Primeira Epístola aos Coríntios, que Ele é o segundo homem (1 Co 15.47). Na Epístola aos Romanos, Ele é o segundo Adão. Jesus tem duas naturezas: é plenamente Deus e plenamente homem. Sua obra possui dois estágios: encarnação e glorificação. O sacrifico pelo pecado, em Levítico 5.7, tinha duas pombas, mostrando os dois aspectos da salvação. O número dois também fala de comunhão, adição e ajuda (Ec 4.9-12). O Senhor Jesus veio para ter comunhão com o homem, trouxe Deus para dentro do homem e levou o homem para dentro de Deus. Dois também é o número do testemunho. Na Bíblia, todo testemunho precisa de, no mínimo, duas pessoas. Os discípulos foram enviados aos pares (Mt 10), porque o testemunho duplo é fiel e verdadeiro (Dt 17.6; 19.15; Mt 18.16; 2 Co 13.1; 1 Tm 5.19). Dois é o testemunho de Cristo. A bíblia fala que os pães que ficavam no Lugar Santo eram dois, o que aponta para o testemunho. Durante a Grande Tribulação haverá duas testemunhas que irão pregar em Jerusalém (Ap 11.3). Apocalipse nos mostra que um dos nomes de Jesus é a Testemunha Fiel e Verdadeira (AP 1.5 e 19.13). Dependendo do contexto, o dois também pode significar divisão e contraste.",

      "Existem três números na Palavra de Deus que significam completude: o três, o sete e o doze. Eles possuem basicamente o mesmo significado, indicando algo completo. O número três, porém, aponta para algo completo relacionado a Deus que é Triuno, três que são um. O homem é a imagem e semelhança de Deus, por isso, ele é triuno: espírito, alma e corpo. A família para ser família tem que ter pai, mãe e filho, porque expressa o relacionamento da trindade. Três também é o número da ressurreição porque Ele ressuscitou ao terceiro dia. Jonas ficou três dias no ventre do peixe e o Senhor disse que esse era o sinal da ressurreição. O batismo é feito em nome do Pai, do Filho e do Espírito Santo. Pedro negou Jesus três vezes e por três vezes Jesus lhe perguntou se ele o amava. A Primeira Epístola de João menciona três testemunhas sobre a terra e o céu (1 Jo 5.8). Elas são o Espírito, a Palavra e o Sangue, testemunhas porque apontam para as três pessoas da trindade.",

      "O quatro é o número da criação. São quatro os elementos: terra, ar, água e fogo. Apocalipse 7.1 mostra que são quatro os ventos da terra. Isso não significa que na Terra existam quatro ventos, mas que eles sopram sobre toda a criação. São quatro as estações do ano e também os pontos cardeais: norte, sul, leste, oeste. São quatro os impérios mundiais mencionados no Livro de Daniel, de Nabucodonosor até Cristo. Os quatro evangelhos narram a história de Jesus vivendo nesse mundo, lidando com sua criação. Na parábola do semeador, são quatro os tipos de solo do coração, mostrando que abrange toda a criação de Deus. O julgamento do mundo tem quatro aspectos em Apocalipse: a guerra, a fome, a doença e o terremoto. Por isso o número quatro na Bíblia, aponta para criação.",

      "O número cinco significa responsabilidade diante do Senhor. Na parábola das virgens, tem-se dois grupos: cincos néscias e cinco prudentes (Mt 25.2). Isso porque cinco significa responsabilidade. É o número de dedos da nossa mão indicando que temos compromisso com os nossos atos. Nossas mãos simbolizam nossas obras. A consagração de Arão e a purificação do leproso tinham cinco unções que eram aplicadas em cinco partes do corpo, mostrando que somos responsáveis pela unção recebida. O Senhor multiplicou cinco pães para alimentar cinco mil pessoas e Davi usou cinco pedras para vencer Golias. Sabemos que o quinto reino mencionado em Daniel, será o reino de Cristo e para entrar nele, temos que ter compromisso. Em Levítico temos cinco ofertas que falam das obrigações de o homem se apresentar diante de Deus. Dessa forma, o número cinco simboliza responsabilidade diante do Pai.",

      "É o número do diabo (Dn 3.1, Ap 13.18). É também o número do homem caído em rebelião contra Deus e unido com o diabo. Seis é o número do homem criado vivendo sem Deus no mundo. O homem foi criado no sexto dia. Pode trabalhar seis dias por semana (Ex 23.12). O número do anticristo é 666. Três vezes seis. Lembra-se que o três significa completude, portanto 666 simboliza o homem em teimosia tentando ser Deus. É o ápice do humanismo e da sua independência de Deus. No Velho Testamento, um escravo só podia ser escravo por seis anos; no sétimo, ele tinha que sair livre. Segundo a cronologia bíblica, a história do homem na Terra tem seis mil anos de Adão até hoje. Entendemos que o sétimo será o milênio. O sexto selo fala da ira do Cordeiro sobre a humanidade. Golias tinha seis dedos nas mãos, seis dedos nos pés e seis côvados de altura. Tudo em Golias era seis, porque fala do homem como inimigo de Deus (1 Sm 17.4-7). Também as dimensões da estátua de Nabucodonosor eram sessenta por seis, mostrando que é um tio de anticristo (Dn 3.1-3). O anticristo se levantará contra tudo que se chama Deus. Ele é a consumação de Babel. É o homem vivendo independente de Deus, dizendo: não precisamos de ti, não queremos nos sujeitar a ninguém, nem adorar a ninguém, não queremos nos dobrar diante de ninguém. O anticristo é o ápice do humanismo. Cada vez mais ouvimos a mensagem de que o homem é o centro, de que o homem é capaz de tudo, de que ele, homem, é o seu próprio Deus.",

      "O número sete tem o mesmo significado do três: completude e perfeição. Mas enquanto o número três é a perfeição de Deus, o número sete é a perfeição de Sua ação na história, no tempo e na Igreja. A partir do número sete, todos os números são uma composição dos seis anteriores. Ele é normalmente a soma de três mais quatro. Três é o número do Deus Triuno unido com a sua criação representada pelo número quatro. Tudo que fala da ação divina no tempo e no meio da sua criação é sete. Por isso o sétimo dia, o sábado, foi santificado (Gn 2.1-3). Enoque, o sétimo depois de Adão, foi transladado (Gn 5.24). Depois que Noé entrou na arca, houve ainda sete dias de tolerância, de graça (Gn 7.4). Jacó serviu a Labão por sete anos. No Egito, houve sete anos de abundância e sete anos de fome. O candelabro tinha sete lâmpadas. O sangue tinha que ser aspergido sete vezes significando a redenção perfeita. O sábado é o sétimo dia simbolizando o perfeito descanso que Deus nos oferece. Durante a festa dos Pães asmos, havia uma oferta de holocausto feita por sete dias, simbolizando a perfeita consagração. A festa dos tabernáculos durava sete dias, simbolizando a perfeita glória. A luta contra Jericó foi feita com sete sacerdotes, usando sete trombetas, marchando por sete dias, simbolizando perfeita vitória. Naamã mergulhou sete vezes no rio Jordão, entendido como perfeita purificação, Jó teve sete filhas depois da sua tribulação, simbolizando a perfeita benção. Jesus falou sete palavras na cruz. Havia sete diáconos na Igreja primitiva. São sete as parábolas do reino em Mateus 13. São sete as festas que havia em Israel e também sete as igrejas em Apocalipse. Nele, existem muitos grupos de sete: são sete espíritos de Deus, sete candelabros, sete lâmpadas, sete chifres, sete olhos, sete trombetas, sete pragas e sete taças. Ao todo, em Apocalipse, o sete é mencionado cinqüenta e seis vezes, portanto compreender o significado desse número é muito importante para o entendimento deste livro.",

      "O número oito significa ressurreição ou novo começo. Na verdade, a ressurreição é um novo começo. É alguém que morreu, ressuscitou e está tendo um novo começo. Por isso, o domingo é o nosso dia de descanso, pois é o dia da ressurreição. O domingo, para nós, não é o primeiro dia; para nós é o oitavo, o dia do recomeço, da nova criação. A Bíblia fala que oito pessoas saíram da arca, simbolizando ressurreição, porque passaram pela morte no dilúvio e saíram para uma nova vida. A circuncisão ocorria no oitavo dia, porque circuncidar significa cortar a carne, daí ter que ser ao oitavo dia para simbolizar ressurreição. Davi era o oitavo filho. O leproso era purificado no oitavo dia. As primícias eram trazidas no oitavo dia. O sacerdote trabalhava no oitavo dia da consagração. A transfiguração se deu no oitavo dia para mostrar que depois da ressurreição nós seremos glorificados (Lc 9.28-36).",

      "O número nove não aparece em Apocalipse. Ele tem dois significados: pode significar ingratidão, pois foram nove os leprosos que não voltaram para agradecer (Lc 17.11-19). Ou pode significar uma obra humana incompleta: pois o nove é a combinação de quatro mais cinco, ou seja, a criação mais a responsabilidade. É por isso que se têm nove dons do Espírito, nove frutos da carne e nove frutos do espírito.",

      "O dez simboliza Totalidade, isto é, a perfeição natural do mundo. Na palavra de Deus, o dez normalmente é composto de cinco mais cindo ou seis mais quatro. Cinco mais cinco nos fala de responsabilidade dobrada, ou seja, completa responsabilidade. É por isso que o sistema que usamos é decimal e fala da responsabilidade de todo homem. Eram dez os mandamentos. Dez eram as virgens e dez foram as pragas no Egito. Os discípulos oraram dez dias. Eram dez os servos em Lucas 19.13."
    ];

    // Exibe a mensagem correspondente
    var mensagemElement = document.getElementById("mensagem");
    mensagemElement.textContent = mensagens[numeroEscolhido - 1];
  } else {
    // Se o número não estiver no intervalo correto, exibe uma mensagem de erro
    alert("Por favor, escolha um número entre 1 e 10.");
  }
}